theme = "hugo-narrow"
baseURL = "https://navnee1h.github.io/"
languageCode = "en-us"
title = "Navnee1h"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# permalinks
[permalinks]
  posts = "/posts/:slug/"
  pages = "/:slug/"

# pagination
[pagination]
  pagerSize = 6
  path = "page"

# taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"

# internationalization - list languages you want
[languages]
  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    weight = 1

# site params (theme-specific)
[params]
  description = "Documenting my cybersecurity journey, pentesting notes."
  keywords = ["cybersecurity", "pentesting", "eJPT", "ethical hacking", "notes","ceh preperation","quantum security","oscp","post quantum cryptography","navaneeth m s","navaneeth","navnee1h"]
  defaultAuthor = "Navaneeth"
  language = "en-US"
  shortName = "MyBlog"
  images = ["/images/Navaneeth-m-s.avif"]

  [params.logo]
    image = "https://raw.githubusercontent.com/navnee1h/navnee1h.github.io/refs/heads/main/public/images/profile.jpg"
    link = ""     # This becomes https://navnee1h.github.io/myblog/ automatically

  [params.favicon]
    svg = "/favicon.svg"


  # UI
  showThemeSwitch = true
  showDarkModeSwitch = true
  showLanguageSwitch = false
  languageSwitchMode = "dropdown"
  stickyHeader = true
  dock = "float"
  colorScheme = "default"
  # Themes card
  [params.themes]
    [params.themes.default]
      name = "Default"
      order = 1
    [params.themes.claude]
      name = "Claude"
      order = 2
    [params.themes.dracula]
      name = "Dracula"
      order = 3
    [params.themes.bumblebee]
      name = "bumblebee"
      order = 4

  # author card
  [params.author]
    name = "Navaneeth M S"
    title = "Security Researcher"
    description = "Studying and documenting my journey."
    avatar = "https://raw.githubusercontent.com/navnee1h/navnee1h.github.io/refs/heads/main/public/images/profile.jpg"

  # social links (used by theme)
  [[params.author.social]]
    name = "GitHub"
    url = "https://github.com/navnee1h"
    icon = "github"
  [[params.author.social]]
    name = "Linkedin"
    url = "https://linkedin.com/in/navnee1h"
    icon = "linkedin"
  [[params.author.social]]
    name = "Email"
    url = "mailto:navaneethms182@gmail.com"
    icon = "email"

# menus
[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10
    params.icon = "posts"

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 20
    params.icon = "categories"

  [[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = 40
    params.icon = "archive"

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 50
    params.icon = "about"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[services]
  [services.googleAnalytics]
    id = "G-7SM0DFG7FG"

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = false
